name: PR Review

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Config File
      run: |
        sed -i "s|GFT_LICENCE|${{ secrets.GFT_LICENCE }}|g" config.yaml
        sed -i "s|AZ_OPENAI_ENDPOINT|${{ secrets.AZ_OPENAI_ENDPOINT }}|g" config.yaml
        sed -i "s|AZ_OPENAI_TOKEN|${{ secrets.AZ_OPENAI_TOKEN }}|g" config.yaml
        sed -i "s|AZ_OPENAI_ENGINE|${{ secrets.AZ_OPENAI_ENGINE }}|g" config.yaml
        sed -i "s|GITHUB_TOKEN|${{ secrets.GH_TOKEN }}|g" config.yaml
        sed -i "s|GITHUB_REPOSITORY|$GITHUB_REPOSITORY|g" config.yaml
        sed -i "s|GITHUB_BASE_REF|${{ secrets.GH_BASE_BRANCH }}|g" config.yaml

        cat config.yaml


    - name: Install GFT CLI
      run: |
        dotnet tool install gftcli --version 1.0.9 --tool-path ./tools

    - name: Run GFT Code Review
      run: |
        ./tools/gft codereview --config_path config.yaml --pullnumber ${{ github.event.pull_request.number }}